config/routes.rb
Rails.application.routes.draw do


  resources :items, only: [:new, :create, :show, :destroy, :edit, :update]

  get 'store' => 'store#index'
  get 'store/order'
  get 'store/manage'
  
  

  resources :messages, only: [:new, :create, :index]

  root             'static_pages#home'
 
  resources :shifts,          only: [:new, :create, :destroy, :edit, :update, :index]
  get 'schedule'  => 'shifts#schedule'
  get 'scheduler'  => 'shifts#scheduler'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'about'   => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'schedule'   => 'static_pages#schedule'
  get 'songhistory'   => 'static_pages#history'
  get 'lineup'  => 'static_pages#lineup'
  get 'donate'  => 'static_pages#donate'
  get 'advertise'  => 'static_pages#advertise'
  get 'weather'  => 'static_pages#weather'
  get 'beine'    => 'static_pages#beine'
  get 'closings' => 'static_pages#closings'
  
  resources :staffs
  
  resources :blogposts
  
  resources :podcasts
  get 'pod_shows' => 'podcasts#shows'
  
  resources :shows
  
  resources :events
  get 'promo' => 'events#promo'
  get 'concerts' => 'events#concerts'
  get 'submit_event' => 'events#submit'
  get 'approve_event' => 'events#approve'
  
  get 'hq'   => 'back_end_pages#main'
  get 'carousel'   => 'back_end_pages#add_carousel'
  get 'mancar'   => 'back_end_pages#manage_car'
  get 'manage_staff'   => 'back_end_pages#manage_staff'
  
  get '/bfg', to: redirect('/shows/3')
  
  resources :articles,          only: [:new, :show, :create, :destroy, :edit, :update]
  get 'news'  => 'articles#news'
  get 'sports'  => 'articles#sports'
  get 'station_news'  => 'articles#station_news'
  
  
  get 'reservations/submit'
  get 'reservations/approve'
  get 'reservations/calendar'
  get 'reservations/info'
  get 'reservations/approve_reservation'
  
  resources :images,          only: [:create, :index, :destroy, :update]
  
  resources :top_tens
  
  resources :account_activations, only: [:edit, :update]
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '*path', to: 'static_pages#home'
  
  resources :staffs do
    member do
        patch :make_admin
        put :make_admin
      end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @images = Image.carousel
    @blogs = Blogpost.limit(3)
    @podcasts = Podcast.limit(3)
    @events = Event.concert.future.limit(6)
  end

  def about
  end
  
  def contact
  end
  
  def schedule
  end
  
  def weather
  end
  
  def history
  end
  
  def lineup
  end
  
  def donate
  end
  
  def advertise
  end

  def beine
  end
  
  def closings
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def onair(shifts)
        now = Time.now
        day = now.strftime("%A")
        shifts = shifts.select {|s| day == s.day.strftime("%A")} 
        shifts = shifts.select{ |s| s.start.strftime("%H") <= now.strftime("%H") && s.end.strftime("%H") > now.strftime("%H")}
        return shifts.first
    end
end

app/views/static_pages/about.html.erb
<div class="col-sm-8">
	<div class="wapper">
		<h1 class="page-title"> About WVBR-FM </h1><hr>
		<h2> Who We Are</h2>
		<p>Based in Ithaca, NY, WVBR broadcasts on 93.5 FM and online at WVBR.com.</p>
		<p>Our 93.5 FM radio signal is broadcast from high atop Hungerford Hill in Ithaca at 3,000 watts, Our online stream is identical to the FM radio broadcast but allows people to listen around the world.</p>
		<p>Our studios are located at 604 East Buffalo Street in Ithaca, NY. If you've won a prize or just want to say hi, stop or come by, Monday-Friday 9am-5pm. Unlike some other local stations, all the music and talk you hear is coming from right here from our East Hill studios...except of course, when we're broadcasting at events throughout the community.</p>
		<p>WVBR is special and unusual among the radio industry. We aren't a part of any media conglomerations -we have been operated by the Cornell Media Guild, Inc. (formerly The Cornell Radio Guild, Inc.) since 1935, an independent, nonprofit media organization in Tompkins County unaffiliated with the University and serving the Tompkins County area. The station is managed and staffed by Cornell University students and community volunteers, most of whom are here because they love music, news, sports and interacting with the local community. As a not-for-profit membership corporation, WVBR provides students with hands-on training in broadcast media and running a multi-faceted business while providing the community with a source for both local and world-class content.</p>
		
		<h2>Where We Come From</h2>
		<p>Our origins trace back to 1935, when Cornell students formed the Cornell Radio Guild, an organization that produced radio content for WESG, a university radio station. The Guild produced and broadcasted content from Willard Straight Hall on the Cornell campus and became incorporated as a non-profit membership corporation in 1941. The organization went on to start providing their own "carrier-current" broadcasts to the Cornell dormitories in the early 40's. Broadcasts were mostly classical music back then and remained so as WVBR hit the FM dial for the first time in 1958. The Cornell Radio Guild was one of a small handful of student-run nonprofit radio stations that successfully applied for and received a commercial FM radio license for the purposes of training its young up-and-coming staff. Some of these stations have since faded away, but WVBR has endured among its fellows WUVA, WBRU, WHRB, and WPRB. In 1968 WVBR switched over to playing rock music. We continued to pioneer the format, joining other legendary stations such as WNEW WMMS, KSAN, and WCMF in the progressive rock revolution through the 70's. The history of the 1958-68 Classical & Jazz Era remains enshrined in current <%= link_to("George E. Beine '61 Studio A.", beine_path) %> </p>
		<p>Since then, the Ithaca spectrum has filled up with stations streamed in from all over the nation, but we have continued to do what we do best - provide independent radio to an independent community. WVBR is the only place you'll place you'll find local music, local news, and local sports alongside the best alternative out there. Plus, you'll see us out in the community - whether we're running a promotion, MCing your favorite summer festival, or it's just our staff working and playing in the community we all live.</p>
		<p>Our programming is as diverse as the community we serve. During the week, we spin the best alternative there is. At night, we have VBR After Dark, where play all the great alternative you hear during the day and expand our music catalog to include the best alternative and independent rock. Every weekend brings a new set of sounds to your ears as we explore the roots of rock through our diverse selection of specialty shows. Everything from blues to oldies and reggae to world music, including Bound for Glory on Sunday night, America's longest continually running folk music show. Whatever your tastes, there's certain to be something that tickles your fancy on WVBR's weekends.</p>
		<p>Being a training ground for broadcast media is part of our mission. WVBR has alumni in every part of the media industry, all the way from on-air personalities to upper management. Besides being a great experience, WVBR can be a great place to start a career in broadcast media.</p>
		<p>We're WVBR: a community of passionate individuals sharing our love of music, news, sports, and everything else with the Ithaca community and the world through our radio station and this website. If you've got any questions or comments, drop us a line. We'd love to hear from you!</p>
	</div>
</div>

<div class="col-sm-4">
	<%= render 'shared/aside' %>
</div>

app/views/static_pages/advertise.html.erb
<div class="col-sm-8">
	<div class="wapper">
		<h1 class="page-title"> Advertise on WVBR-FM </h1><hr>
		 
		<h4>WVBR can help promote your organization, business or event to the Ithaca community and beyond. Increase the visibility of your business or organization.  Advertise on WVBR and be heard! <br> <br>
			For more infomation, please contact our sales manager: <br> <br> John Rudan <br>
			
			Send a message to: jr(at)wvbr.com<br>
			Call: (607)273-4000 x 1
			</h4>
	</div>

</div>


<div class="col-sm-4">
  
	<%= render 'shared/aside' %>

</div>

app/views/static_pages/beine.html.erb
<div class="wapper">
    <div class="cbox">
    <h1> The George E. Beine '61 Studio A </h1>
    <p><b>George Beine symbolizes WVBR-FM’s classical and jazz era (c. 1958 – 68) and its presence in the basement of Willard Straight Hall, next to the Rock Garden, from 1948 to 1972. The alumni of the classical and jazz era honored George and their days at WVBR by naming the main production studio the "George E. Beine '61 Studio A."</b></p>
    <hr>
    <div style="float:right; margin:20px"><%= image_tag("Plaque.jpg", width: "280")  %> </div>
    <p>Beine was probably the finest announcer of that era, with a deep, calm voice particularly suited to the format. This is an (almost) serious clip of George in his usual role of classical music announcer.</p>


    <%= audio_tag("beine.mp3", controls: true) %>

    

    <p>Back in the 1960s, MJ Productions of Columbus, Ohio ran an ad in Billboard offering a sample package of five station breaks for $2. 
    Someone at VBR made this investment. Suffice it to say that at 40 cents apiece, the breaks were a bit overpriced. 
    However, the VBR staff took them as a challenge, and responded by producing their own five ads for MJ. 
    This clip from one of them includes snippets of MJ's original offerings and the voice of George Beine. 
    The full history and full recordings of these tongue-in-cheek MJ Breaks is available <a target="blank" href="http://wvbr.toolworks.com/memorabilia.html">here.</a>
    </p>
    <%= audio_tag("MJ_Breaks.mp3", controls: true) %>
  
    <h3>
        Memories of George
    </h3>
    
    <p>
        "George was more than a voice. I remember him reading the summary of the opera from the back of the jacket live on the air. When he gave it to me to put the record away I realized it was in German. I know there were others who could have done that, but would they?" - Steve Gauss
    </p>
    <div style="float:left; margin:10px"><%= image_tag("Beine Yearbook.jpg", width: "500")  %> </div>
    <p>
        "Don't know some of the other classical announcers over the years, but George brought a set of "pipes" that most of the rest of us envied!" - Ray Voss
    </p>
    <p>
        "Any number of aspiring announcers, me included, longed for the invention of a 'George Beine Machine' to lower the pitch of our voices without changing the speed." - Tom Preston
    </p>
    <p>
        "I also used to be his engineer for recording the classical music program (all the breaks for the week
        were taped in one session). Early in his career at WVBR, George also read news. Once, while he was
        reading from a long tear sheet (a very long sheet of news torn off from our teletype machine) we lit the
        bottom of the paper. As the flames approached the part George was reading he never missed a beat,
        his beautiful delivery never changed. When the flames reached his fingers he dropped the burning
        sheets and finished the newscast with never a tremor."
    </p>
    
    <h3>Life</h3>
    <p>Beine was born in Rochester, NY on September 29, 1939. He attended Benjamin Franklin High School there before matriculating in 1956 at Cornell where he studied Electrical Engineering, receiving a Bachelor of degree in 1961 and a Master of Science in 1964. He was reportedly first in his class.</p>

    <p>Beine went on to become a Professor of Electrical Engineering at the University of Cincinnati, and president of Gnomon, Inc. in Cincinnati. He was a member of the Institute of Electrical and Electronic Engineers (IEEE), the Technical Association of the Pulp and Paper Industry (TAPPI), and the Association for Computing Machinery (ACM).</p>
    
    <p>George Beine died on March 11, 1989 at the age of 49.</p>
    
    <h3>Studio A Today</h3>
    <p style="margin:10px">Below, WVBR celebrates its Ribbon Cutting and new home in Studio A on March 15, 2014</p>
    
    <div style="float:left; margin:10px"><%= image_tag("gb-1.JPG", width: "470")  %> </div>
    <div style="float:right; margin:10px"><%= image_tag("gb-2.JPG", width: "470")  %> </div>
    
    <p style="clear:both; margin: 10px;">Studio A serves as the home of WVBR's record library and main production capabilities. It is the source of Tuesdays with the Band
    and allows local and traveling artists to be heard on air. The beautiful, record-lined space with clever sound insulation provides an optimal performance area. </p>
    <div style="margin:10px;"><%= image_tag("gb-3.JPG", width: "700")  %> </div>
    
    </div>
</div>

app/views/static_pages/closings.html.erb
<div class="wapper">
	<h1 class="page-title"> Ithaca Area Closings and Cancellations </h1><hr> 
	<pre>
		<object data="http://ithacanet.org/closingsdetail.html" width="100%" height="300"><embed src="http://ithacanet.org/closingsdetail.html" width="100%" height="300"></object>
	</pre>
	<!-<iframe name="closings" src="http://ithacanet.org/closingsdetail.html" frameborder="0" scrolling="auto"></iframe>
</div>

app/views/static_pages/contact.html.erb
<div class="col-sm-8">
	<div class="wapper">
		<h1 class="page-title"> Contact WVBR </h1><hr>
		<h3 class="center">New music submissions: music@wvbr.com </h3>
		<h3 class="center"> <%= link_to  'Click here', 'submit_event' %> to submit an event to the Concert Log or Community Calendar</h3>
		<h3 class="center"> General contact: info@wvbr.com</h3>
		<h3 class="center"><b>
			Want to get involved with local radio? Whether your interest is DJing, news, engineering or programming, we'd love to have you
			join the WVBR family! Email info(at)wvbr.com for more information.
		</b></h3>
	</div>
</div>
<div class="col-sm-4">
  	<%= render 'shared/aside' %>
	<br>
</div>

app/views/static_pages/donate.html.erb
<div class="col-sm-8">
	<div>
        <div class="wapper">
            <h1 class="page-title"> Help Support the Station! </h1><hr>
            <p>WVBR-FM is operated by the Cornell Media Guild Inc., a 501(c)(3) non-profit organization. We are managed primarly by Cornell University students and operate independently of,
	and are not funded by, Cornell University.  Generous donations received from community members and alumni are an essential supplement to advertising revenue.
	All donations further our mission to train students for radio and help prepare for careers in media and are critical to maintaining the operation of the station. We appreciate your support!
	Thank you!
            <br>Donations to WVBR are tax-deductible.
            <hr>
            </p>
            <h3 class="center">How to Donate?</h3>
            <p><b>Send a check addressed to WVBR-FM</b><br>
            604 E. Buffalo St.<br> Ithaca, NY 14850</p>
            
            <p><b>Give via Paypal by clicking the button below</b></p>
            <div style="width:200px;">
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="blank">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="W9H5TZUVKXPW2">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
            </div>
        </div>

	</div>

</div>


<div class="col-sm-4">
  
	<%= render 'shared/aside' %>

</div>

app/views/static_pages/history.html.erb
	<div class="col-sm-8">
		<div class="wapper">
			<h1>WVBR Song History</h1>
			<hr>
			<p> <b>Our DJs sometimes play music off of CD and vinyl (and sometimes we even have live performers!). Due to these unique formats, we do not always 
			have every song automatically appear on this list. In that case, your best bet is to contact the DJ at 607-273-2121 as close as possible to the time you 
			hear the song. Some hosts will also post their playlists, so check their individual blogs. We are unfortunately not able to answer emails asking
			about songs heard at a specific time. </b></p>
			<hr>
			
			<%
			lines = Array.new
			f = open('http://scripts.wvbr.com/935-song-history.txt')
			lines = []
			f.each_line do |line|
				lines << line
			end
			len = lines.length
			(1..len).each do |n|
			%>
			<p><%= lines[len-n].force_encoding('UTF-8') %></p>
			<%
			end
			f.close() 
			%>
		
		</div>
    
	</div>
 

	<div class="col-sm-4">
      
		<%= render 'shared/aside' %>
   
	</div>
  

app/views/static_pages/home.html.erb
<% meta_tag :description, "WVBR FM a non-profit organization and community radio station broadcasting out of Ithaca NY." %>



<!--Main Casosol Here-->

<div id="home-1" class="body-element">
	

	<div id="carousel" class="carousel slide carousel-fade">
	  <% n = @images.size %>
		<div class="carousel-inner">
		<div class="active item"><img src="/assets/home-1.png"/></div>
		<% @images.each do |image| %>
		    <div class="item"><%= image_tag image.picture.url  %> </div>
		<% end %>
		<a class="carousel-control left" href="#carousel" data-slide="prev">  </a>
		<a class="carousel-control right" href="#carousel" data-slide="next">  </a>
		</div>
		  
	</div>

  
</div>


<div class="body-element w-ad">
</div>
<!--# blogs and 3 podcasts featured below-->
<div id="home-2" class="body-element">


	<% @blogs.each do |blog| %>
		<% if blog.picture? %>
			<div class="img-box"  style="background-image: url(<%= blog.picture%>)">
		<% else %>
			<div class="img-box">
		<%end%>
	    
	        <div class="box-title"> 
	            <h4><%= link_to blog.title, blog  %></h4>
	        </div>
	    </div>
	<% end %> 

	<% @podcasts.each do |pod| %>
	    <div class="img-box" style="background-image: url(<%= pod.image.picture if pod.image %>)">
	        <div class="box-title"> 
	            <h4><%= link_to pod.title, pod  %></h4>
	        </div>
	    </div>
	<% end %> 
	
</div>

<div id="home-3" class="body-element">
  <div class="cal-block">
    
    <h3 class="center">UPCOMING EVENTS</h3>
    
    <% @events.each do |event| %>
    	<div class="event">
		    <div class="date">
		    	<h2>
		    		<%= event.date.strftime('%^b')%> <br>
		    		<%= event.date.strftime('%e')%>
		    	</h2>
		    </div>
		    <p><%= link_to event.name, event  %></p>  
       		<p><%= event.location %></p>
		</div>
    <% end %>
  </div>
  
  <div class="cal-block">
    <h3 class="center">FEATURED</h3>
    <hr>
    <div id="hangar-ad">
    	<a target="blank" href="http://www.hangartheatre.org/"> <img  src="/assets/hangar.jpg" width="300"/> </a>
    	<hr>
    </div>
    <div id="hangar-ad">
    	<a target="blank" href="http://www.kitchentheatre.org/"><img src="/assets/ktclogo.jpg" width="300"/></a>
    	<hr>
    </div>
		</div>
</div>




<script>
	$(document).ready(function(){
		$('#carousel').carousel();
		
		$('.dropable').click(function(){
			$('#closings').animate({
           		height: $('#closings').get(0).scrollHeight
       		}); 
		});
		$('#hide').click(function(){
			$('#closings').animate({
           		height: '50px'
       		}); 
		});
	});
</script>

app/views/static_pages/lineup.html.erb
<div class="wapper">
    <h1 class="page-title"> Typical Weekday Line up </h1><hr>
    
    <h2>Morning Alternative - 6:00am - 12:00pm</h2>
    <p>Playing Ithaca's best Alternative mix. VBR has a massive library of music that taps into the deepest cuts that you didn't even know existed.
    Real Rock in the Morning will take you down the path of Forgotten Favorites every week, refreshing your 
    memory about some well-buried music that deserves another spin. Look out for some great new music along the way too!</p>
    
    <h2>The Lunch Hour - 12:00pm - 3:00pm</h2>
    <p>Spend the second half of the work day with your favorite DJ's on WVBR. Guaranteed to provide the
    perfect mix to get you through the afternoon!</p>
    
    <h2>The Afternoon Drive - 3:00pm - 7:00pm</h2>
    <p>Finish up your work day and enjoy the drive home with WVBR. All your favorite alternative hits with 
    News, and Weather every hour to keep you caught up on everything you need to know. Stay tuned to WVBR to make your afternoon fly by.</p>
    
    <h2>VBR AfterDark - 7:00pm-5:00am</h2>
    <p>Want to hear something new? Then VBR AfterDark is the place to be! Every weeknight from 7pm to 5am, VBR AfterDark brings you the same mix of alternative hits that you love along with some great deep tracks and music from lesser known artists.</p>
    
    <h2>The Top 10 at 10</h2>
    <p>Every weeknight at 10pm, the VBR DJs count down the Top 10 of something! The DJs will pick a topic and select what they think are the 10 best songs relating to that topic.</p>

</div>

</div>

<!- This page needs to be completely redone for the rebrand - Kevin ->

app/views/static_pages/weather.html.erb
<div class="col-sm-8">
	<div class="wapper">
		<h1 class="page-title"> WVBR Weather Center </h1><hr>
		<a href="http://www.accuweather.com/en/us/ithaca-ny/14850/weather-forecast/334655" class="aw-widget-legal">
		<!--
		By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at http://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at http://www.accuweather.com/en/privacy.
		-->
		</a><div id="awtd1464316524951" class="aw-widget-36hour"  data-locationkey="334655" data-unit="f" data-language="en-us" data-useip="false" data-uid="awtd1464316524951" data-editlocation="true"></div><script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>		
	</div>
</div>
<div class="col-sm-4">
	<%= render 'shared/aside' %>
</div>