config/routes.rb
Rails.application.routes.draw do


  resources :items, only: [:new, :create, :show, :destroy, :edit, :update]

  get 'store' => 'store#index'
  get 'store/order'
  get 'store/manage'
  
  

  resources :messages, only: [:new, :create, :index]

  root             'static_pages#home'
 
  resources :shifts,          only: [:new, :create, :destroy, :edit, :update, :index]
  get 'schedule'  => 'shifts#schedule'
  get 'scheduler'  => 'shifts#scheduler'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'about'   => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'schedule'   => 'static_pages#schedule'
  get 'songhistory'   => 'static_pages#history'
  get 'lineup'  => 'static_pages#lineup'
  get 'donate'  => 'static_pages#donate'
  get 'advertise'  => 'static_pages#advertise'
  get 'weather'  => 'static_pages#weather'
  get 'beine'    => 'static_pages#beine'
  get 'closings' => 'static_pages#closings'
  
  resources :staffs
  
  resources :blogposts
  
  resources :podcasts
  get 'pod_shows' => 'podcasts#shows'
  
  resources :shows
  
  resources :events
  get 'promo' => 'events#promo'
  get 'concerts' => 'events#concerts'
  get 'submit_event' => 'events#submit'
  get 'approve_event' => 'events#approve'
  
  get 'hq'   => 'back_end_pages#main'
  get 'carousel'   => 'back_end_pages#add_carousel'
  get 'mancar'   => 'back_end_pages#manage_car'
  get 'manage_staff'   => 'back_end_pages#manage_staff'
  
  get '/bfg', to: redirect('/shows/3')
  
  resources :articles,          only: [:new, :show, :create, :destroy, :edit, :update]
  get 'news'  => 'articles#news'
  get 'sports'  => 'articles#sports'
  get 'station_news'  => 'articles#station_news'
  
  
  get 'reservations/submit'
  get 'reservations/approve'
  get 'reservations/calendar'
  get 'reservations/info'
  get 'reservations/approve_reservation'
  
  resources :images,          only: [:create, :index, :destroy, :update]
  
  resources :top_tens
  
  resources :account_activations, only: [:edit, :update]
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '*path', to: 'static_pages#home'
  
  resources :staffs do
    member do
        patch :make_admin
        put :make_admin
      end
  end
  
end

app/controllers/back_end_pages_controller.rb
class BackEndPagesController < ApplicationController
    before_action :logged_in_staff
    
    def main
    end

    def add_carousel
        @image = Image.new
    end
    
    def manage_car
        @images = Image.carousel
    end
    
    def manage_staff
        @aa = Staff.activated
        @in = Staff.unactivated
    end

    
end

app/helpers/back_end_pages_helper.rb
module BackEndPagesHelper
end

app/views/back_end_pages/add_carousel.html.erb
<div class="wapper">
  <%= form_for(@image, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.hidden_field :catergory, :value => 'carousel' %>
    
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    
    <div class="field">
      <%= f.text_area :description, placeholder: "Add description for image..." %>
    </div>
    
    <%= f.label :expire, "Set date to remove image from carousel (optional)" %>
    <%= f.date_field :expire, class: 'form-control' %>
    
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
      <%= f.file_field :picture %>
    </span>
  <% end %>
</div>

app/views/back_end_pages/blog.html.erb
<h1>DJs post individual blogs</h1>

<section class="blogpost_form">
      
  <%= form_for(@blogpost, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
      <% end %>
  
  </section>
  
  <script type="text/javascript">
  $('#blogpost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/back_end_pages/main.html.erb
<div class="wapper">
    <div class="col-md-8 col-md-offset-2 wapper">
        <h1> Admin Home </h1>
        <hr>
        <h4>Welcome! If you are new to the site, we will have some instructions up here soon. 
            If you want to work with web content, please contact the web team (akk77)
        </h4>
        <br>
        <h4><b>Staff</b></h4>
        <p><%= link_to "Add staff",   new_staff_path %></p>
        <p><%= link_to "See All Staff",   manage_staff_path %></p>
        
        <h4><b>Content</b></h4>
        <p><%= link_to "Manage Carousel Content",   mancar_path %></p>
        <p><%= link_to "Add Slide to Carousel",   carousel_path %></p>
        
        <h4><b>Community<b></h4>
        <p><%= link_to "Event Submissions",   approve_event_path %></p>
        <p><%= link_to "Messages",   messages_path %></p>
    </div>
</div>
    

app/views/back_end_pages/manage_car.html.erb
<div class="col-sm-8">
	<div class="wapper">
		<h1>Manage Home Page Carousel</h1>
        <h4><%= link_to "Add to carousel",   carousel_path %></h4>
        <hr>
        <% @images.each do |image| %>
        <%= image_tag(image.picture.url, width: "50%")  %>
        <p><%= image.title  %></p>
        <p>
            <%= image.description  %> 
            <%= link_to "Remove from carousel", image, method: :delete, data: { confirm: "You sure?" } %>
        </p>
        <hr>
        <% end %> 
    </div>
</div>

app/views/back_end_pages/manage_staff.html.erb
<div class="wapper">

<h2> Activated Users (<%= @aa.size %>)</h2>


<% @aa.each do |s| %>
    <hr>
    <h5><%= s.name %></h5>
    <p><%= s.email %></p>
        <% if logged_in? && current_staff.admin? && !current_staff?(s) %>
            <%= link_to "delete |", s, method: :delete,
                                      data: { confirm: "You sure?" } %>
            <%= link_to "edit", edit_staff_path(s) %>
            <%= link_to "| Make Admin", make_admin_staff_path(s), method: :put if !s.admin? %>
        <% end %>
        
<% end %>




<h2> Unactivated Users  (<%= @in.size %>)</h2>


<% @in.each do |s| %>
<hr>
    <p><%= s.email %></p>
      <% if logged_in? && current_staff.admin? && !current_staff?(s) %>
    | <%= link_to "delete", s, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
<% end %>
</div>