config/routes.rb
Rails.application.routes.draw do


  resources :items, only: [:new, :create, :show, :destroy, :edit, :update]

  get 'store' => 'store#index'
  get 'store/order'
  get 'store/manage'
  
  

  resources :messages, only: [:new, :create, :index]

  root             'static_pages#home'
 
  resources :shifts,          only: [:new, :create, :destroy, :edit, :update, :index]
  get 'schedule'  => 'shifts#schedule'
  get 'scheduler'  => 'shifts#scheduler'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'about'   => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'schedule'   => 'static_pages#schedule'
  get 'songhistory'   => 'static_pages#history'
  get 'lineup'  => 'static_pages#lineup'
  get 'donate'  => 'static_pages#donate'
  get 'advertise'  => 'static_pages#advertise'
  get 'weather'  => 'static_pages#weather'
  get 'beine'    => 'static_pages#beine'
  get 'closings' => 'static_pages#closings'
  
  resources :staffs
  
  resources :blogposts
  
  resources :podcasts
  get 'pod_shows' => 'podcasts#shows'
  
  resources :shows
  
  resources :events
  get 'promo' => 'events#promo'
  get 'concerts' => 'events#concerts'
  get 'submit_event' => 'events#submit'
  get 'approve_event' => 'events#approve'
  
  get 'hq'   => 'back_end_pages#main'
  get 'carousel'   => 'back_end_pages#add_carousel'
  get 'mancar'   => 'back_end_pages#manage_car'
  get 'manage_staff'   => 'back_end_pages#manage_staff'
  
  get '/bfg', to: redirect('/shows/3')
  
  resources :articles,          only: [:new, :show, :create, :destroy, :edit, :update]
  get 'news'  => 'articles#news'
  get 'sports'  => 'articles#sports'
  get 'station_news'  => 'articles#station_news'
  
  
  get 'reservations/submit'
  get 'reservations/approve'
  get 'reservations/calendar'
  get 'reservations/info'
  get 'reservations/approve_reservation'
  
  resources :images,          only: [:create, :index, :destroy, :update]
  
  resources :top_tens
  
  resources :account_activations, only: [:edit, :update]
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '*path', to: 'static_pages#home'
  
  resources :staffs do
    member do
        patch :make_admin
        put :make_admin
      end
  end
  
end

app/models/show.rb
class Show < ActiveRecord::Base
    has_and_belongs_to_many :staffs
    has_many :blogposts, as: :blogable, dependent: :destroy
    has_many :images, as: :imageable, dependent: :destroy
    has_many :podcasts
    accepts_nested_attributes_for :images, :reject_if => lambda { |a| a[:picture].blank? }, :allow_destroy => true
    
    validates :name, presence: true
    validates :description, presence: true
    validates :catergory, inclusion: { in: %w(specialty podcast)}, allow_blank: true
    validates :end, presence: true, if: :specialty?
    validates :start, presence: true, if: :specialty?
    validates_presence_of :images
    
    scope :specialty, -> { where(catergory: 'specialty') } 
    scope :podcast, -> { where(catergory: 'podcast') } 

    def specialty?
        catergory == "specialty"
    end
    
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :logged_in_staff, only: [:create, :new, :edit, :update, :delete]
    before_action :can_access, only: [:create, :new, :edit, :update, :delete]
    before_action :admin_staff, only: [:delete, :new, :create]
    
    def index
        @specialty_shows = Show.specialty
    end
    def show
        @show = Show.find(params[:id])
    end
    
    def new
        @show = Show.new
        @show.images.build
    end
    def create
        @show = Show.new(show_params)
        if @show.save
            show_staff
            flash[:success] = "Show Created!"
            redirect_to shows_path
        else
            render 'new'
        end
    end
    
    def edit
        @show = Show.find(params[:id])
        @show.images.build
    end
  
    def update
        @show = Show.find(params[:id])
        if @show.update_attributes(show_params)
          show_staff
          flash[:success] = "Show updated"
          redirect_to @show
        else
          render 'edit'
        end
    end
    
    def destroy
        Show.find(params[:id]).destroy
        flash[:success] = "Show deleted"
        redirect_to shows_url
    end
    
    private
    
        def show_params
          params.require(:show).permit(:name, :description, :day, :start, :end, :catergory,
                        :images_attributes => [:id, :title, :descrption, :expire, :catergory, :picture])
        end
        
        def can_access
            @show = current_staff.shows.find_by(id: params[:id])
            redirect_to root_url unless !(@show.nil?) || current_staff.admin?
        end
        
        def show_staff
            @show.staffs.each do |s|
                idn = s.id.to_s.to_sym
                rem = params[idn][:remove]
               @show.staffs.delete(s) if  rem == "1"
            end
            staff_ids = params[:choice]
            staff_ids.each do |id|
                if id.to_i > 0
                    s = Staff.find(id) 
                    @show.staffs << s
                end
            end
        end
end

app/views/shows/_show.html.erb
    <div class="ashow" style="background-image: url(<%= show.images.first.picture.url if show.images.first.picture? %>)"> 
                        
    <div>
    <h2><%= link_to show.name, show  %></h2>
     <hr>
    <p><%= simple_format(truncate(show.description, length: 250))  %></p>
    </div>
    </div>
   

app/views/shows/edit.html.erb
<section class="wapper blogpost_form">
  <h1>Edit Show</h1>
  <hr>
  <%= form_for(@show, :html => {:multipart => true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.label :catergory %>
    <%= f.select :catergory, options_for_select([["specialty"], ["podcast"]], @show.catergory), class: 'form-control' %>
    
    <b>Current DJs:</b>
    <% if @show.staffs.any? %>
      <% @show.staffs.each do |s| %>
        <br> <%= s.name %> :
        <%= check_box(name=s.id, "remove") %> Check to remove this DJ
      <% end %>
    <% else %>
      <p>None</p>
    <% end %>
    <br>
    <b> Add DJs affiliated with this show</b>
    <% staff = Staff.all.active.map { |s| [s.name, s.id] } %>
    <% staff << ["Select DJ", 0] %>
    <% 2.times do %>
      <%= select_tag(name="choice[]", options_for_select(staff, 0)) %>
    <% end %>
    
        Images:
      <ul class="image-form">
        <%= f.fields_for :images do |builder| %>
          <%= render "images/image_fields", :f => builder %>
        <% end %>
      </ul>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 10, class: 'form-control' %>

      <%= f.label :day %>
      <%= f.select :day, options_for_select([["Monday"], ["Tuesday"], ["Wednesday"], ["Thursday"], ["Friday"], ["Saturday"], ["Sunday"]], @show.day), class: 'form-control' %>
      
      <%= f.label :start %>
      <%= f.time_field :start, class: 'form-control' %>
      
      <%= f.label :end %>
      <%= f.time_field :end, class: 'form-control' %>


      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  
  </section>

app/views/shows/index.html.erb
<div class="body-element"> 
  <div class="wapper">
      <div class="page-2">
        <h1 class="page-title"> Specialty Shows </h1><hr>
        <%= render @specialty_shows %>
      </div>
      <div class="page-1">
      <%= render 'shared/aside' %>
      </div>
    
  </div>
</div>

app/views/shows/new.html.erb
<section class=" wapper blogpost_form">
  <h1>New Show</h1>
  <hr>
  <%= form_for(@show, :html => {:multipart => true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.label :catergory %>
    <%= f.select :catergory, options_for_select([["specialty"], ["podcast"]]), class: 'form-control' %>
    
    <b> Select DJs affiliated with this show</b>
    <% staff = Staff.active.activated.map { |s| [s.name, s.id] } %>
    <% staff << ["Select DJ", 0] %>
    <% 3.times do %>
      <%= select_tag(name="choice[]", options_for_select(staff, 0)) %>
    <% end %>
    
      <b>Image:</b>
      <ul class="image-form">
        <%= f.fields_for :images do |builder| %>
          <%= render "images/image_fields", :f => builder %>
        <% end %>
      </ul>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 10, class: 'form-control' %>

      <%= f.label :day %>
      <%= f.select :day, options_for_select([["Monday"], ["Tuesday"], ["Wednesday"], ["Thursday"], ["Friday"], ["Saturday"], ["Sunday"]]), class: 'form-control' %>
      
      <%= f.label :start %>
      <%= f.time_field :start, class: 'form-control' %>
      
      <%= f.label :end %>
      <%= f.time_field :end, class: 'form-control' %>


      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  
  </section>

app/views/shows/show.html.erb
  <div class="wapper">
    <div class="col-sm-8">

        <div class="wapper showshow">
          <h1> <%= @show.name %> </h1>
          
            <% if @show.catergory === "specialty" %>
              <h4><%= @show.day %> | <%= @show.start.strftime("%I:%M%p") %> - <%= @show.end.strftime("%I:%M%p") %></h4>
              <p>
              <% sh =  @show.staffs.map{|s| s.name }%>
              <%= sh.to_sentence %>
              </p>
            <% end %>
        
                <% if logged_in? && (current_staff.admin?) %>
                    <p><%= link_to "edit", edit_show_path(@show) %>
                    | <%= link_to "delete", @show, method: :delete,
                    data: { confirm: "You sure?" } %>
                    | <%= link_to "post a blog", new_blogpost_path(@show) %></p>
                <% end %><hr>

        <% if @show.images.exists? %>
            <% @show.images.each do |image| %>
                <div class="center"><%= image_tag(image.picture.url, width: 600) %></div>
            <% end %>
        <% end %>
        <hr>
        <p><%= simple_format(@show.description) %> </p>
        <br><br>
        
        <% if @show.blogposts.any? %>
        <h2>Posts from us</h2>
        
        <% @show.blogposts.each do |blogpost| %><hr>
        <h3><%= link_to blogpost.title, blogpost %></h3>
        
        <span class="timestamp">
            <%= link_to blogpost.staff.name, blogpost.staff %>
            | Posted <%= time_ago_in_words(blogpost.created_at) %> ago.
            <% if logged_in? && current_staff?(blogpost.staff) %>
              <%= link_to "delete", blogpost, method: :delete,
                                               data: { confirm: "You sure?" } %>
            <% end %>
        </span>
        <p><%= blogpost.subtitle %></p>
        <% end %> 
        <% end %> 
        
        <br>
        
        <% if  @show.podcasts.any? %>
        <h2>Podcasts</h2><hr>
          <% @show.podcasts.each do |podcast| %>
            <div>
              <h2><%= link_to podcast.title, podcast %></h2>
              <span class="timestamp">
                Posted <%= time_ago_in_words(podcast.created_at) %> ago.
                <% if current_staff?(podcast.staff) %>
                  <%= link_to "delete", podcast, method: :delete, data: { confirm: "You sure?" } %>
                <% end %>
                  </span>
                  <p>Genre: <%= podcast.catergory %></p>
                  
                  <audio controls>
                  <source src=<%= podcast.audio.url %> type="audio/mp3">
                  Your browser does not support the audio element.
                  </audio>

            </div>
         <% end %>
        <% end %>
        
        </div>
        
        </div>
    <div class="col-sm-4">
      <%= render 'shared/aside' %>
  </div>
</div>